[package]
name = "csv-sort-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.29.1"
egui_plot = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
rand = "0.8"
fake = { version = "2.9", features = ["derive"] }
chrono = "0.4"
rfd = "0.15"
